pipeline {
    agent any
 
    tools {
        maven 'Maven installations'
        jdk 'jdk25'
    }
 
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/pratha25/Para-Bank-Automation-.git'
            }
        }
 
        stage('Build') {
            steps {
                dir('ParaBankAutomationFramework') {
                    bat 'mvn clean compile'
                }
            }
        }
 
        stage('Run Tests') {
            steps {
                dir('ParaBankAutomationFramework') {
                    bat 'mvn test'
                }
            }
        }
    }
 
    post {
        always {
            archiveArtifacts artifacts: '**/target/surefire-reports/*, **/test-output/**/*, **/screenshots/**/*',
                             allowEmptyArchive: true
        }
 
        success {
            echo 'Build Successful!'
        }
 
        failure {
            echo 'Build Failed!'
        }
    }
}